name: fc_domain
description: Dart package encapsulates the domain logic for the Flut Cast app, facilitating business rules implementation, data processing, and interaction between different parts of the application.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  fc_common:
    path: ../fc_common
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0