name: flut_cast
description: "FlutCast: Weather app powered by Flutter"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  fc_api_client:
    path: packages/fc_api_client
  fc_common:
    path: packages/fc_common
  fc_data:
    path: packages/fc_data  
  fc_domain:
    path: packages/fc_domain
  fc_geolocator:
    path: packages/fc_geolocator  
  fc_local_storage:
    path: packages/fc_local_storage  
  fc_ui:
    path: packages/fc_ui
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.4
  hooks_riverpod: ^2.5.1  
  intl: ^0.18.1
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod: ^2.5.1
  sembast: ^3.7.1
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  slang_build_runner: ^3.30.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/clear_sky.frag
    - shaders/clouds.frag
    - shaders/drizzle.frag
    - shaders/rain.frag
    - shaders/snow.frag
    - shaders/thunderstorm.frag
