targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - "lib/src/result/result.dart"
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
