targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - "lib/src/helpers/either.dart"
            - "lib/src/failures/http_request_failure.dart"
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
