name: fc_common
description: Dart package provides custom exceptions, typedefs, and the Either class to enhance functional programming in Flut Cast.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0